### ISSUE TITLE
Api does not work

### ISSUE THREAD

**Issue by TeamAggroDEV** [Mokulu/discord-oauth2-api#2]
The API does not work anymore, when i try to get user Informations, i get this error: 
`org.jsoup.HttpStatusException: HTTP error fetching URL. Status=401, URL=https://discordapp.com/api/users/@me
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:682)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:629)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:261)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:250)
        at io.mokulu.discord.oauth.DiscordAPI.handleGet(DiscordAPI.java:53)
        at io.mokulu.discord.oauth.DiscordAPI.fetchUser(DiscordAPI.java:58)
        at de.AggroMC.AggroBot.Webinterface.Dashboard.getServerList(Dashboard.java:16)
        at de.AggroMC.AggroBot.Webinterface.Dashboard.handle(Dashboard.java:53)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
        at java.lang.Thread.run(Thread.java:748)
`
What can i do to fix this issue?

**Comment by Bedi58** [comment]
Can you pls screenshot the whole error and your implementation? For me it works fine.

**Comment by Mokulu** [comment]
You must have the scope `identify` to access user info. If you don't have that, you'll need to include it in the instantiation of DiscordOAuth and then re-authorize the user with the new authorization URL.

If you are using the identify scope already, then it could be the access token you're passing is expired. Pass the refresh token that was provided with the invalid access token to DiscordOAuth.refreshTokens method to get a new set of tokens.
